-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg/+OO7O0Ne8lHRRVd
biFAlBadq9y5KgavHP+NBPCNQxigCgYIKoZIzj0DAQehRANCAATGIjAlMTjybxPC
Bjn0Ndrh3Uy0D4qudqKU/j/hjF7/SxdI/hi4ysxe7Rs5GuvAJOxIYVIpRt6y48la
U0N/e6QJ
-----END PRIVATE KEY-----